# Copyright (c) 2018-2022 The MobileCoin Foundation
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "fogServices.fullname" . }}-fog-view-grpc
  labels:
    app: fog-view
    {{- include "fogServices.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.global.certManagerClusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.global.certManagerClusterIssuer }}
    {{- end }}
    {{ toYaml (tpl .Values.fogView.ingress.grpc.annotations . | fromYaml)| nindent 4 }}
spec:
  tls:
  - hosts:
    - {{ include "fogServices.fogPublicFQDN" . }}
    secretName: {{ include "fogServices.fogPublicFQDN" . }}-fog-tls
  rules:
  - host: {{ include "fogServices.fogPublicFQDN" . }}
    http:
      paths:
      - path: /fog_view.FogViewAPI
        pathType: Prefix
        backend:
          service:
            # Hack: this ing should be managed by fog router now as that should front all
            # gRPC traffic to fog-view
            name: fog-router-blue
            port:
              number: 3225
