[package]
name = "mc-util-serial"
version = "4.0.0-pre0"
authors = ["MobileCoin"]
edition = "2021"

[features]
# Build everything with std flags turned on. This is generally needed in targets that use std
# because rmp-ser../../alloc doesn't build against ser../../std,
# so if anything else in your build plan will activate ser../../std, then mcseri../../std is
# required.
std = ["serde/std", "serde_cbor/std", "serde_with"]
test_utils = ["protobuf"]
prost = [ "dep:prost", "protobuf" ]
serde = [ "dep:serde", "serde_cbor", "serde_with" ]

default = [ "std", "prost", "serde" ]


[dependencies]
prost = { version = "0.11", optional = true, default-features = false, features = ["prost-derive"] }
protobuf = { version = "2.27", optional = true }
serde = { version = "1.0", optional = true, default-features = false, features = ["alloc", "derive"] }
serde_cbor = { version = "0.11.1", optional = true, default-features = false, features = ["alloc"] }
serde_with = { version = "2.0", optional = true, default-features = false, features = ["macros"] }

[dev-dependencies]
serde_json = "1.0"
