[package]
name = "mc-transaction-signer"
version = "4.0.0-pre0"
authors = ["MobileCoin"]
edition = "2021"
readme = "README.md"

[features]


[dependencies]
# External dependencies
anyhow = "1.0.66"
displaydoc = { version = "0.2", default-features = false }
serde = { version = "1.0",  default-features = false, features = ["derive"] }
serde_json = "*"
subtle = { version = "2.4.1", default-features = false, features = ["i128"] }
zeroize = { version = "1", default-features = false }
clap = { version = "4.0.26", features = [ "derive" ]}
tiny-bip39 = "1.0"
log = "0.4.17"
hex = { version = "0.4.2", default_features = false }
rand_core = "0.6.4"

# MobileCoin dependencies
mc-account-keys = { path = "../../account-keys" }
mc-common = { path = "../../common", default-features = false, features = ["loggers"] }
mc-core = { path = "../../core", features = [ "serde" ] }
mc-core-types = { path = "../../core/types", features = [ "serde" ] }
mc-crypto-keys = { path = "../../crypto/keys", default-features = false }
mc-crypto-ring-signature = { path = "../../crypto/ring-signature", default_features = false }
mc-crypto-ring-signature-signer = { path = "../../crypto/ring-signature/signer", default_features = false }
mc-transaction-core = { path = "../../transaction/core", default_features = false }
mc-transaction-extra = { path = "../../transaction/extra", default_features = false }
mc-transaction-summary = { path = "../../transaction/summary", default_features = false }
mc-transaction-types = { path = "../../transaction/types", default_features = false }

mc-util-repr-bytes = { path = "../../util/repr-bytes", default-features = false }
mc-util-serial = { path = "../../util/serial", default-features = false }

[[bin]]
name = "mc-transaction-signer"
path = "src/main.rs"
