[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1", features = ["derive", "env"] }
mc-api = { path = "../../api" }
mc-blockchain-types = { path = "../../blockchain/types" }
mc-common = { path = "../../common" }
mc-consensus-scp = { path = "../../consensus/scp" }
mc-ledger-sync = { path = "../../ledger/sync" }
mc-transaction-core = { path = "../../transaction/core" }
mc-watcher = { path = "../../watcher" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
