[package]
name = "mc-sgx-compat"
version = "1.3.0-pre0"
authors = ["MobileCoin"]
edition = "2018"

# All dependencies are optional
[dependencies]
cfg-if = "1.0"
mc-sgx-types = { path = "../types" }

[target.'cfg(target_env = "sgx")'.dependencies]
mc-sgx-alloc = { path = "../alloc" }
mc-sgx-panic = { path = "../panic" }
mc-sgx-sync = { path = "../sync" }
mc-sgx-debug = { path = "../debug" }
mc-sgx-service = { path = "../service" }
