apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fog-router.fullname" . }}
  labels:
    {{- include "fog-router.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fog-router.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fog-router.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fog-router.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-router
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: 3225
              protocol: TCP
          command:
          - /usr/bin/supervisord
          resources:
            limits:
              intel.com/sgx: 2k
            requests:
              intel.com/sgx: 2k
          {{- with .Values.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end}}
          envFrom:
          - secretRef:
              name: ias
          volumeMounts:
            - mountPath: /etc/supervisor/conf.d
              name: supervisor-conf
            - mountPath: /var/run/aesmd
              name: aesm-socket-dir

      volumes:
      - emptyDir: {}
        name: aesm-socket-dir
      - name: supervisor-conf
        projected:
          defaultMode: 420
          sources:
          - configMap:
              name: fog-services-supervisord-sgx
          - configMap:
              name: fog-services-supervisord-daemon
          - configMap:
              name: fog-services-supervisord-admin
          - configMap:
              name: {{ include "fog-router.fullname" . }}-router
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
