apiVersion: v1
kind: Service
metadata:
  name: {{ include "fog-router.fullname" . }}
  labels:
    {{- include "fog-router.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "fog-router.selectorLabels" . | nindent 4 }}
