[package]
name = "mc-transaction-types"
version = "4.0.0-pre0"
authors = ["MobileCoin"]
edition = "2021"
readme = "README.md"

[features]
std = [ "prost?/std" ]
serde = [ "dep:serde", "mc-crypto-keys/serde", "mc-crypto-ring-signature/serde" ]
prost = [ "dep:prost", "mc-crypto-keys/prost", "mc-crypto-ring-signature/prost" ]
alloc = [
    "serde?/alloc",
    #"mc-crypto-keys/alloc",
    #"mc-crypto-dalek/alloc",
]

default = [ "std", "alloc", "serde", "prost", "mc-crypto-dalek/default" ]

[dependencies]
# External dependencies
displaydoc = { version = "0.2", default-features = false }
crc = { version = "3.0.0", default-features = false }
prost = { version = "0.11", optional = true, default-features = false, features = ["prost-derive"] }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive"] }
subtle = { version = "2.4.1", default-features = false, features = ["i128"] }
zeroize = { version = "1", default-features = false }
hkdf = "0.12"
sha2 = { version = "0.10", default-features = false }

# MobileCoin dependencies
mc-crypto-dalek = { path = "../../crypto/dalek", default-features = false }
mc-crypto-digestible = { path = "../../crypto/digestible", default-features = false, features = ["dalek", "derive"] }
mc-crypto-keys = { path = "../../crypto/keys", default-features = false }
mc-crypto-hashes = { path = "../../crypto/hashes", default-features = false }
mc-crypto-ring-signature = { path = "../../crypto/ring-signature", default-features = false }

