[package]
name = "mc-transaction-extra"
version = "4.0.0-pre0"
authors = ["MobileCoin"]
edition = "2021"

[features]
serde = [
    "dep:serde",
    "mc-transaction-types/serde",
    "mc-transaction-summary/serde",
    "mc-crypto-dalek/serde",
    "mc-util-repr-bytes/serde",
    "mc-util-serial/serde",
]
prost = [
    "dep:prost",
    "mc-transaction-types/prost",
    "mc-transaction-summary/prost",
    "mc-util-repr-bytes/prost",
    "mc-util-serial/prost"
]

default = [
    "serde",
    "prost",
    "mc-crypto-dalek/default",
    "mc-crypto-digestible/default",
    "mc-crypto-hashes/default",
    "mc-util-repr-bytes/default",
]

[dependencies]
# External dependencies
cfg-if = "1.0"
displaydoc = { version = "0.2", default-features = false }
hmac = "0.12"
prost = { version = "0.11", optional = true, default-features = false, features = ["prost-derive"] }
rand = { version = "0.8", default-features = false }
rand_core = { version = "0.6", default-features = false }
serde = { version = "1.0", optional = true, default-features = false, features = ["alloc", "derive"] }
sha2 = { version = "0.10", default-features = false }
subtle = { version = "2", default-features = false }
zeroize = "1"

# MobileCoin dependencies
mc-account-keys = { path = "../../account-keys", default_features = false }
mc-core = { path = "../../core", default_features = false }
mc-crypto-dalek = { path = "../../crypto/dalek", default_features = false }
mc-crypto-digestible = { path = "../../crypto/digestible", default_features = false, features = ["dalek"] }
mc-crypto-hashes = { path = "../../crypto/hashes", default_features = false  }
mc-crypto-keys = { path = "../../crypto/keys", default-features = false }
mc-crypto-ring-signature = { path = "../../crypto/ring-signature", default_features = false }
mc-crypto-ring-signature-signer = { path = "../../crypto/ring-signature/signer", default_features = false }
mc-transaction-core = { path = "../../transaction/core", default_features = false }
mc-transaction-types = { path = "../../transaction/types", default_features = false }
mc-transaction-summary = { path = "../../transaction/summary", default_features = false }
mc-util-from-random = { path = "../../util/from-random" }
mc-util-repr-bytes = { path = "../../util/repr-bytes", default_features = false }
mc-util-serial = { path = "../../util/serial", default_features = false }
mc-util-vec-map = { path = "../../util/vec-map" }
mc-util-zip-exact = { path = "../../util/zip-exact" }

curve25519-dalek = { version = "4.0.0-pre.2", default-features = false, features = ["nightly"] }

[dev-dependencies]
assert_matches = "1.5"
maplit = "1.0"
yaml-rust = "0.4"

mc-fog-report-validation-test-utils = { path = "../../fog/report/validation/test-utils" }
mc-transaction-builder = { path = "../../transaction/builder", features = ["test-only"] }
mc-util-from-random = { path = "../../util/from-random" }
mc-util-test-helper = { path = "../../util/test-helper" }
