[package]
name = "mc-ledger-streaming-client"
version = "1.3.0-pre0"
authors = ["MobileCoin"]
license = "MIT OR Apache-2.0"
edition = "2018"

[features]
test_utils = []

[dependencies]

mc-common = { path = "../../../common" }
mc-api = { path = "../../../api" }
mc-consensus-scp = { path = "../../../consensus/scp" }
mc-ledger-streaming-api = { path = "../api" }
mc-transaction-core = { path = "../../../transaction/core" }
mc-util-grpc = { path = "../../../util/grpc" }
mc-util-uri = { path = "../../../util/uri" }
mc-ledger-db = { path = "../../../ledger/db" }

displaydoc = { version = "0.2", default-features = false }
futures = { version = "0.3.21" }
grpcio = { version = "0.10.0" }
protobuf = { version = "2.22.1" }
async_executors = { version = "0.5.1" }
structopt = { version = "0.3" }
serde_json = "1.0"
tokio = { version = "1.17.0" }
pin-project = {version = "1.0.10" }

[build-dependencies]
mc-util-build-grpc = { path = "../../../util/build/grpc" }
mc-util-build-script = { path = "../../../util/build/script" }

cargo-emit = "0.2.1"

[dev-dependencies]
mc-common = { path = "../../../common", features = ["loggers"] }
mc-consensus-scp = { path = "../../../consensus/scp", features = ["test_utils"] }
mc-ledger-db = { path = "../../../ledger/db", features = ["test_utils"] }
mc-util-test-helper = { path = "../../../util/test-helper" }
