[package]
name = "mc-sgx-alloc"
version = "5.1.1"
authors = ["MobileCoin"]
license = "GPL-3.0"
readme = "README.md"
# TODO: Consider making sgx a self-contained workspace and get the value from there.
rust-version = "1.68.0"

[dependencies]
mc-sgx-debug = { path = "../debug" }
lazy_static = "1.4"
mc-sgx-sync = { path = "../sync" }
[features]
default = ["oom_panic"]
oom_panic = []
oom_abort = []
